config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }


  resources :products do
    resources :comments
  end

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]


  root 'static_pages#landing_page'

  get 'static_pages/about'

  get 'static_pages/contact'
  
  get 'static_pages/index'


  post 'static_pages/thank_you'
  post '/payments/create'

  mount ActionCable.server => '/cable'  #  run ActionCable within the same process as the rest of the app 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_footer.html.erb
<footer class="navbar-fixed-bottom">
  <div class="container-fluid">
    &copy; <%= Date.today.year %> Riot Bikes 
    <% if user_signed_in? %>
    <div class="dropdown" id="usermenu">
      <button class="btn dropdown-toggle" type="button"  data-toggle="dropdown">
      Logged in as <%= current_user.email %>  
      <span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="usermenu">
        <li role="presentation"><%= link_to 'Userlist', users_path, role: "menuitem" %></li>
        <li role="presentation"><%= link_to 'Show Profile', current_user, role: "menuitem"  %></li>
        <li role="presentation" class="divider"></li>
        <li role="presentation"><%= link_to 'Edit Profile', edit_user_registration_path, role: "menuitem"  %></li>
      </ul>
    </div>
    <% end %>
  </div>
</footer>

app/views/shared/_head.html.erb
<title>Riot Bikes</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/shared/_header.html.erb
<title>Riot Bikes</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to('Riot Bikes', root_path, class: "navbar-brand navbar-btn") %>  
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to('products', products_path) %></li>
        <li><%= link_to('about', static_pages_about_path) %></li>
        <li><%= link_to('contact', static_pages_contact_path) %></li>
      </ul>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to("Logout", destroy_user_session_path, :method => :delete, class: "navbar-btn redbtn") %></li>
        <% else %>
        <li><%= link_to("Login", new_user_session_path, class: "navbar-btn greenbtn") %></li>
        <li><%= link_to("Sign up", new_user_registration_path, class: "navbar-btn")  %></li>
        <% end %>
      </ul>
      <%= form_tag("/products", method: "get", class: "navbar-form navbar-right") do %>
      <div class="form-group">
        <%= label_tag(:q, "Search for:", class: "sr-only") %>
        <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search for bikes") %> <!-- nil --> 
      </div>
      <%= submit_tag("Go!", class: "btn btn-default navbar-btn") %>
      <% end %> 
    </div>
  </div>
  <div class="container-fluid">
    <%= render "shared/notifications" %>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<% if notice %>
 <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
 <p id ="alert" class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="<%= image_path @product.image_url %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= (@product.price*100) %>" // Stripe expects the price you give it to be an integer in cents
  data-currency="eur">
</script>
<%= hidden_field_tag :product_id, @product.id %>